### ISSUE TITLE
Syntax error due to nullish coalescing

### ISSUE THREAD

**Issue by wolfy1339** [gr2m/release-notifier-action#147]
```
/home/runner/work/_actions/gr2m/release-notifier-action/v1/dist/index.js:4319
  onUnhandledRequest ?? (onUnhandledRequest = onUnhandledRequestDefaultNode);
                      ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by wolfy1339** [comment]
It seems to be coming from `@octokit/auth-oauth-app`
